name: projectasahi
description: ProjectAsahi Home Page
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.9.0
  simple_animations: ^2.2.1
  easy_web_view: ^1.2.0
  fluro: "^1.6.3"
  flutter_svg: ^0.17.3+1
  photo_view: ^0.9.2
  universal_html: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/asahi/