name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter channel master
    - run: flutter upgrade
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release
