name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'master'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release
